# Generated by Django 4.2 on 2023-06-09 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0017_rename_sipplierof_table_ordered_products_column_supplierof_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordered_products_table',
            options={'ordering': ['-dateof_Creating']},
        ),
        migrations.AlterField(
            model_name='tableitem',
            name='product_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
