# Generated by Django 4.2 on 2023-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0018_alter_ordered_products_table_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
