# Generated by Django 4.2 on 2023-06-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_alter_debt_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekTRable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekStart', models.DateField(auto_now=True)),
                ('weekEnd', models.BooleanField(default=False)),
            ],
        ),
    ]
