# Generated by Django 4.2 on 2023-06-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0021_weektrable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeekTRable',
            new_name='WeekTables',
        ),
    ]
