# Generated by Django 4.2 on 2023-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_rename_weektrable_weektables'),
    ]

    operations = [
        migrations.AddField(
            model_name='weektables',
            name='weekTable',
            field=models.CharField(default='Table', max_length=255),
        ),
    ]
