# Generated by Django 4.2 on 2023-06-24 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0024_weektables_customerweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableitem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JoinedTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableName', models.CharField(max_length=250, null=True)),
                ('dateOfCreating', models.DateField(auto_now=True, null=True)),
                ('timeOfCreating', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timeOfCreating'],
            },
        ),
        migrations.AddField(
            model_name='usertable',
            name='joinedTable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.joinedtables'),
        ),
    ]
