# Generated by Django 4.2 on 2023-06-25 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0025_tableitem_customer_joinedtables_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableName', models.CharField(max_length=250, null=True)),
                ('dateOfCreating', models.DateField(auto_now=True, null=True)),
                ('timeOfCreating', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timeOfCreating'],
            },
        ),
    ]
