# Generated by Django 4.2 on 2023-06-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0026_singletable'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='singleTable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.singletable'),
        ),
    ]
