# Generated by Django 4.2 on 2023-06-27 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0028_remove_debt_is_return_remove_debt_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='joinedtables',
            name='dateOfCreating',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='singletable',
            name='dateOfCreating',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='dateOfCreating',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Paymant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('returned', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('timeOfCreating', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
