# Generated by Django 4.2 on 2023-06-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0029_alter_debt_date_alter_joinedtables_dateofcreating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymant',
            options={'ordering': ['-timeOfCreating']},
        ),
        migrations.RemoveField(
            model_name='debt',
            name='seen',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
