# Generated by Django 4.2 on 2023-07-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0035_remove_bigtablerows_bigtable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigtablerows',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.usertable'),
        ),
    ]
