# Generated by Django 4.2 on 2023-07-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0037_tableitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='old_debt',
            name='until',
            field=models.DateField(null=True),
        ),
    ]
