# Generated by Django 4.2 on 2023-08-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0038_old_debt_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsmodel',
            name='supPrice',
            field=models.IntegerField(null=True),
        ),
    ]
