# Generated by Django 4.2 on 2023-08-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0039_itemsmodel_supprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableitem',
            name='supTotal',
            field=models.IntegerField(null=True),
        ),
    ]
