# Generated by Django 4.2 on 2023-08-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0040_tableitem_suptotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigtablerows',
            name='supTotal',
            field=models.IntegerField(null=True),
        ),
    ]
