# Generated by Django 4.2 on 2023-08-19 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0041_bigtablerows_suptotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingForChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newTotal', models.IntegerField()),
                ('newCount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('table_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.tableitem')),
            ],
        ),
    ]
