# Generated by Django 4.2 on 2023-08-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0042_waitingforchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingforchange',
            name='dateofCreating',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waitingforchange',
            name='date',
            field=models.DateField(),
        ),
    ]
