# Generated by Django 4.2 on 2023-08-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0043_waitingforchange_dateofcreating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigtablerows',
            name='product_count',
        ),
        migrations.RemoveField(
            model_name='bigtablerows',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='bigtablerows',
            name='supTotal',
        ),
        migrations.RemoveField(
            model_name='bigtablerows',
            name='table',
        ),
        migrations.RemoveField(
            model_name='bigtablerows',
            name='total_price',
        ),
        migrations.AddField(
            model_name='bigtablerows',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.tableitem'),
        ),
    ]
