# Generated by Django 4.2 on 2023-08-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0044_remove_bigtablerows_product_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigtablerows',
            name='porduct_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
