# Generated by Django 4.2 on 2023-09-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0045_bigtablerows_porduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigtable',
            name='modifiedDate',
            field=models.DateField(null=True),
        ),
    ]
