# Generated by Django 4.2 on 2023-10-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0046_bigtable_modifieddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingforchange',
            name='endorsed',
            field=models.BooleanField(default=False),
        ),
    ]
