# Generated by Django 4.2 on 2023-10-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0047_waitingforchange_endorsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingforchange',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
