# Generated by Django 4.0.6 on 2023-10-25 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0048_waitingforchange_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordered_products_column',
            old_name='parent_Table',
            new_name='parentTable',
        ),
        migrations.RemoveField(
            model_name='ordered_products_column',
            name='supplierof_table',
        ),
        migrations.RemoveField(
            model_name='ordered_products_column',
            name='table',
        ),
        migrations.AddField(
            model_name='ordered_products_column',
            name='customerof_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='supplier_Mistakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldCount', models.IntegerField()),
                ('newCount', models.IntegerField()),
                ('date', models.DateField()),
                ('endorsed', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.tableitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ordered_Itmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productCount', models.IntegerField()),
                ('getId', models.IntegerField(null=True)),
                ('parentTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.ordered_products_column')),
            ],
        ),
    ]
