# Generated by Django 4.0.6 on 2024-08-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0049_rename_parent_table_ordered_products_column_parenttable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsmodel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
