# Generated by Django 5.2.1 on 2025-06-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('element_name', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('supplier_id', models.IntegerField(default=0)),
            ],
        ),
    ]
