# Generated by Django 5.2.1 on 2025-06-24 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage_element',
            name='modified_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Tmp_Elements_Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp_val', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage_element')),
            ],
        ),
    ]
