# Generated by Django 5.2.1 on 2025-08-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storage_element_modified_date_tmp_elements_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_Working_Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
    ]
